server:
  type: default
  maxThreads: 1024
  applicationConnectors:
    - port: 8100
      type: http
  adminConnectors:
    - type: http
      port: 8101

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password:
  url: jdbc:mysql://localhost:3306/bookProject